# Generated by Django 3.1.7 on 2021-03-26 16:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('content', models.TextField()),
                ('externalcontent', models.CharField(blank=True, max_length=100, null=True)),
                ('image1', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')),
                ('image2', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')),
                ('image3', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')),
                ('author', models.ManyToManyField(to='blogapi.Author')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
