# Generated by Django 3.1.7 on 2021-03-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(choices=[('US', 'us'), ('World', 'world'), ('Health', 'health'), ('Agriculture', 'agriculture'), ('Finance', 'finance'), ('Military', 'military'), ('Culture', 'culture'), ('Politics', 'politics'), ('Trade', 'trade')], default='World', max_length=12),
        ),
    ]
